# -*- coding: utf-8 -*-
"""Linear_Regression(Predict Home Price).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17GlMEuQ632luNieMR-cEMm6MWZz_u-FJ
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

df = pd.read_csv('homeprices.csv')
df

plt.xlabel("Area(sqr ft)")
plt.ylabel("Price($)")
plt.scatter(df.area,df.price, color='red' ,marker='*')

new_df = df.drop('price',axis='columns')
new_df

price=df.price
price

Reg=linear_model.LinearRegression()
Reg.fit(new_df,price)

area_df=pd.read_csv("areas.csv")
area_df.head(3)

R=Reg.predict(area_df)
R

area_df['prices']=R;
area_df

area_df.to_csv("Prediction Result.csv")